const fs = require('fs');
const path = require('path');

// Get network from command line
const network = process.argv[2];
if (!network) {
  console.error('Please specify a network: hardhat, sepolia, or mainnet');
  process.exit(1);
}

// Validate network
if (!['hardhat', 'sepolia', 'mainnet'].includes(network)) {
  console.error('Invalid network. Choose one of: hardhat, sepolia, mainnet');
  process.exit(1);
}

// Define file path
const envFilePath = path.join(__dirname, '../frontend/.env.local');

// Create or update .env.local file
const envContent = `# Auto-generated by set-network.js
# Network selection (hardhat, sepolia, mainnet)
NEXT_PUBLIC_NETWORK=${network}

# Add your API keys here
NEXT_PUBLIC_INFURA_API_KEY=
NEXT_PUBLIC_ALCHEMY_API_KEY=
`;

// Write to file
fs.writeFileSync(envFilePath, envContent);

console.log(`Network set to ${network} in frontend/.env.local`);
console.log('Remember to add your API keys in the generated file!');

// Instructions based on the selected network
if (network === 'hardhat') {
  console.log('\nTo work with Hardhat network:');
  console.log('1. Run a local Hardhat node:');
  console.log('   npx hardhat node');
  console.log('2. Deploy contracts to local node:');
  console.log('   npx hardhat run scripts/deploy-hardhat.ts --network hardhat');
  console.log('3. Start the frontend:');
  console.log('   cd frontend && npm run dev');
} else if (network === 'sepolia') {
  console.log('\nTo work with Sepolia testnet:');
  console.log('1. Make sure your .env file has PRIVATE_KEY, ETHEREUM_API_KEY, and ETHERSCAN_API_KEY');
  console.log('2. Deploy contracts to Sepolia:');
  console.log('   npx hardhat run scripts/deploy-sepolia.ts --network sepolia');
  console.log('3. Verify contracts:');
  console.log('   npx hardhat run scripts/verify-contracts.ts --network sepolia');
  console.log('4. Start the frontend:');
  console.log('   cd frontend && npm run dev');
} else if (network === 'mainnet') {
  console.log('\n⚠️ MAINNET DEPLOYMENT ⚠️');
  console.log('Make sure you have:');
  console.log('- Completed thorough testing on testnet');
  console.log('- Had your contracts professionally audited');
  console.log('- Sufficient ETH for deployment and gas costs');
  console.log('- Backup of your private key');
  console.log('\nTo deploy to mainnet:');
  console.log('1. Make sure your .env file has PRIVATE_KEY, ETHEREUM_API_KEY, and ETHERSCAN_API_KEY');
  console.log('2. Deploy contracts to mainnet:');
  console.log('   npx hardhat run scripts/deploy-sepolia.ts --network mainnet');
  console.log('3. Verify contracts:');
  console.log('   npx hardhat run scripts/verify-contracts.ts --network mainnet');
  console.log('4. Build the frontend for production:');
  console.log('   cd frontend && npm run build');
} 